server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/project
    username: jungyu
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.user.dto

file:
  location: C:\\Users\\solid\\Desktop\\spring\\file\\

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB  # 최대 파일 크기 설정
    max-request-size: 10MB  # 최대 요청 크기 설정