server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/teamproject
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
    resources:
      static-locations: classpath:/static/

  mail:
    host: smtp.gmail.com
    port: 587
    username: title.jjk1990@gmail.com
    password: qwer1234!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB  # 최대 파일 크기 설정
      max-request-size: 100MB  # 최대 요청 크기 설정

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.user.dto



file:
  location: C:\mn-project\upload


