server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: qweqwe1!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 최대 파일 크기 설정
      max-request-size: 10MB  # 최대 요청 크기 설정

  mail:
    host: smtp.gmail.com
    port: 587
    username: title.jjk1990@gmail.com
    password: qwer1234!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.user.dto

file:
  location: /Users/baegmingyu/work/mn-project/upload